__Arithmetic Operation__

1) a+b -> np.add(a,b)
2) a-b -> np.subtract(a,b)
3) a*b -> np.multiply(a,b)
4) a/b -> np.divide(a,b)
5) a%b -> np.mod(a,b)
6) a**b -> np.power(a,b)
7) 1/a -> np.reciprocal(a)

In [2]:
import numpy as np 

var = np.array([1,2,3,4])

varadd = var + 3
print(varadd)

[4 5 6 7]


In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1+var2
print(varadd)

[2 4 6 8]


In [4]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1/var2
print(varadd)

[1. 1. 1. 1.]


In [5]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1%var2
print(varadd)

[0 0 0 0]


In [6]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1**var2
print(varadd)

[  1   4  27 256]


In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1-var2
print(varadd)

[0 0 0 0]


In [8]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = 1/var2
print(varadd)

[1.         0.5        0.33333333 0.25      ]


In [9]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1*var2
print(varadd)

[ 1  4  9 16]



__2D Array__

In [11]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[2,3,4,5]])

varadd = var1+var2
print(varadd)

[[2 4 6 8]
 [3 5 7 9]]


In [12]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[2,3,4,5]])

varadd = var1/var2
print(varadd)

[[1.         1.         1.         1.        ]
 [0.5        0.66666667 0.75       0.8       ]]


In [13]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[2,3,4,5]])

varadd = var1**var2
print(varadd)

[[   1    4   27  256]
 [   1    8   81 1024]]


In [14]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[2,3,4,5]])

varadd = var1-var2
print(varadd)

[[ 0  0  0  0]
 [-1 -1 -1 -1]]


In [15]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[2,3,4,5]])

varadd = var1%var2
print(varadd)

[[0 0 0 0]
 [1 2 3 4]]


In [16]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[2,3,4,5]])

varadd = var1*var2
print(varadd)

[[ 1  4  9 16]
 [ 2  6 12 20]]


__3D Array__

In [17]:
var1 = np.array([[1,2,3,4],[1,2,3,4],[4,5,6,7]])
var2 = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

varadd = var1+var2
print(varadd)

[[ 2  4  6  8]
 [ 3  5  7  9]
 [ 8 10 12 14]]


In [22]:
var1 = np.array([[1,2,3,4],[1,2,3,4],[4,5,6,7]])
var2 = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

varadd = var1%var2
print(varadd)

[[0 0 0 0]
 [1 2 3 4]
 [0 0 0 0]]


In [23]:
var1 = np.array([[1,2,3,4],[1,2,3,4],[4,5,6,7]])
var2 = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

varadd = var1/var2
print(varadd)

[[1.         1.         1.         1.        ]
 [0.5        0.66666667 0.75       0.8       ]
 [1.         1.         1.         1.        ]]


In [25]:
var1 = np.array([[1,2,3,4],[1,2,3,4],[4,5,6,7]])
var2 = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

varadd = var1-var2
print(varadd)

[[ 0  0  0  0]
 [-1 -1 -1 -1]
 [ 0  0  0  0]]


In [26]:
var1 = np.array([[1,2,3,4],[1,2,3,4],[4,5,6,7]])
var2 = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

varadd = var1**var2
print(varadd)

[[     1      4     27    256]
 [     1      8     81   1024]
 [   256   3125  46656 823543]]
