__Arithmetic Functions__

1) np.min(x)
2) np.max(x)
3) np.argmin(x)
4) np.sqrt(x)
5) np.sin(x)
6) np.cos(x)
7) np.cumsum(x)

In [2]:
import numpy as np 

var = np.array([1,2,3,4,5,2])

print("min:",np.min(var))

min: 1


In [3]:
print("max:",np.max(var))

max: 5


In [5]:
print("argmin: ",np.argmin(var)) #argument minimum
print("argmax: :" ,np.argmax(var))

argmin:  0
argmax: : 4


In [10]:
var1 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(np.min(var1))

1


In [11]:
var1 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(np.max(var1))

6


In [13]:
var1 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(np.sqrt(var1)) #squareroot

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [1.41421356 1.73205081 2.         2.23606798 2.44948974]]


In [14]:
var1 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(np.sin(var1))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]]


In [17]:
var1 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(np.cumsum(var1))  #cumsum calculates the cummulative sum of array elements. It returns a new array of the same shape as the input array,where each element at index i is the sum of all elements up to and including index i in the original array.b

[ 1  3  6 10 15 17 20 24 29 35]


numpy.cumsum(a, axis=None, dtype=None, out=None)

Return the cumulative sum of the elements along a given axis.

