__ARRAY__

__To create a NumPy array, you cna use the function np.array()__





In [8]:
import numpy as np 
a = np.array([1,2,3])
print(a)
print(a.ndim) # ndim provides the dimension of the array

[1 2 3]
1


In [4]:
x= [1,2,3,4,5]

y = np.array(x)
print(y)

print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
l = []

for i in range(1,5):
    int_1 = int(input("enter: "))
    l.append(int_1)

print(np.array(l))

enter:  1
enter:  2
enter:  3
enter:  4


[1 2 3 4]


Dimensios in Arrays

-> 1-D Arrays
-> 2-D Arrays
-> 3-D Arrays
-> Higher Dimensional Arrays


In [10]:
two_dimensional_array= np.array([[1,2,3,4],[2,3,4,5]])
print(two_dimensional_array)

[[1 2 3 4]
 [2 3 4 5]]


The number of column and rows must be same while providing data in array 


In [15]:
ar3 = np.array([[1,2,3,4,5],[3,5,6,7,8],[4,5,6,7,8]])
print(ar3)
print(ar3.ndim)

[[1 2 3 4 5]
 [3 5 6 7 8]
 [4 5 6 7 8]]
2
