CREATING NumPy Arrays Using NumPy Function

Special NumPy Array

Array filled with 0's
Array filled with 1's
Create an empty array
An array with a range of elements
Array diagonal element filled with 1's
Create an array with values that are spaced linearly in a specified interval

In [2]:
import numpy as np 

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


__Ones__


In [3]:
ar_one = np.ones(4)

print(ar_one)


[1. 1. 1. 1.]


__Empty__


In [5]:
ar_em = np.empty(4)
print(ar_em) #Provides the same output as above is due to the memory recalling it 

[1. 1. 1. 1.]


__Range__

In [10]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


__Diagonal__

In [11]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
ar_dia = np.eye(5,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


__linspace function__

generates an array of evenly spaced numbers over a difined interval

In [14]:
ar_lin = np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]
