__Data Types In NumPy Arrays__

In [1]:
import numpy as np 

var = np.array([1,2,3,4])
print("Data Type: ",var.dtype)

Data Type:  int64


In [3]:
var = np.array([1.2,2.2])
print("Data Type: ",var.dtype)

Data Type:  float64


In [5]:
var = np.array(['a','b','b',1,2,3,4])
print("Data Type: ", var.dtype)  #Unicode 

Data Type:  <U21


In [6]:
x= np.array([1,2,3],dtype = np.int8)
print("Data Type: ",x.dtype)
print(x)

Data Type:  int8
[1 2 3]


In [7]:
x= np.array([1,2,3],dtype = "f")
print("Data Type: ",x.dtype)
print(x)

Data Type:  float32
[1. 2. 3.]


In [10]:
x2 = np.array([1,2,3,4,5])
new = np.float32(x2)
print("Data Type: ",x2.dtype)
print("Data Type: ",new.dtype)

print(x2)
print(new)

new_one = np.int_(new)
print(new_one)

Data Type:  int64
Data Type:  float32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [11]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
