__Create NumPy Arrays with Random Numbers__

rand() : the function is used to generate a random vlaue between 0 to 1.

randn(): the function is used to generate a random value close to zero. This may return positive or negative numbers as well.

ranf(): the function for doing random sampling in numpy.It resturns an array of specified shape and fills it with random floats in the half-open inteval [0.0,1.0]

randint(): the function is used to generate a random integers within a specified range (inclusive of both endpoints)


__Random__


__Rand()__

In [1]:
import numpy as np

var = np.random.rand(4)
print(var)


[0.21372491 0.01474148 0.41793869 0.1739888 ]


In [2]:
print(var)

[0.21372491 0.01474148 0.41793869 0.1739888 ]


In [3]:
var1 = np.random.rand(2,5)
print(var1)

[[0.50806842 0.64019384 0.83497973 0.17160943 0.90638682]
 [0.86854344 0.98210847 0.14898233 0.66835254 0.37552672]]



__Randn()__

The fundtion is used to generate a random value close to zero.
This may return positive or negative numbers as well

In [5]:
var2 = np.random.randn(4)
print(var2)

[ 0.02682091  1.43878094 -0.33738768 -0.95748501]


In [6]:
print(var2)

[ 0.02682091  1.43878094 -0.33738768 -0.95748501]


In [10]:
var2_1 = np.random.randn(3,4)
print(var2_1)

[[-0.70531585 -1.11111902 -0.30133605 -0.2541617 ]
 [-1.28237834 -1.53026175  0.01148099  1.7029302 ]
 [-0.52523801 -0.68801686  0.02323798  0.85647612]]


__ranf()__

the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0,1.0]


In [11]:
var3 = np.random.ranf(5)
print(var3)

[0.76686885 0.62893108 0.58655041 0.73135221 0.22908099]


In [12]:
print(var3)

[0.76686885 0.62893108 0.58655041 0.73135221 0.22908099]


In [16]:

var33 = np.random.ranf((3,3,3))
print(var33)

[[[0.61052737 0.31759481 0.60074319]
  [0.27887431 0.72017886 0.14619306]
  [0.65779368 0.68335844 0.25992357]]

 [[0.5694864  0.99753546 0.36481802]
  [0.80598045 0.02286105 0.38023352]
  [0.64887647 0.98277497 0.65746976]]

 [[0.59617442 0.70314418 0.66918467]
  [0.79774631 0.88093083 0.46108933]
  [0.60363363 0.39278492 0.33795569]]]


__randint()__

the function is used to generate a random integers within a specified range(inclusive of both endpoints) 


In [17]:
var4= np.random.randint(4)
print(var4)

2


In [18]:
var44 = np.random.randint((2,4,6))
print(var44)

[1 0 2]


In [19]:
print(var4)

2


In [20]:
var4 = np.random.randint(5,20,5)
print(var4)

[15  8 16 14  5]
